version: '3'
services:
    nginx:
        image: nginx:1.17.3-alpine
        ports:
           - "443:443"
        volumes:
            - "./cert:/cert"
            - "./nginx.conf:/etc/nginx/nginx.conf"